
from itertools import count


a = "Strawberry\tSWEET"
b = "Sweet\bSugarbit"
print(a.capitalize()) #The capitalize() method converts the first character of the string to uppercase and the rest to lowercase. In this case, it will convert "strawberry" to "Strawberry".
print(a.casefold()) #The casefold() method is used to convert a string to lowercase for case-insensitive comparisons. It is similar to the lower() method but more aggressive in converting characters. In this case, it will convert "strawberry SWEET" to "strawberry sweet".
print(a.center(50)) #The center() method centers the string within a specified width. In this case, it will center the string "Strawberry SWEET" within a width of 50 characters.
print(a.count("r")) #The count() method returns the number of occurrences of a substring in the given string. In this case, it counts how many times the letter "r" appears in the string "Strawberry". The result will be 3, as there are three occurrences of "r" in the string.
print(a.encode()) #The encode() method encodes the string using a specified encoding. By default, it uses UTF-8 encoding. In this case, it will convert the string "Strawberry SWEET" into a bytes object.
print(a.endswith("t")) #The endswith() method checks if the string ends with a specified suffix. In this case, it checks if the string "Strawberry SWEET" ends with the letter "t". The result will be False, as the string ends with "T" (uppercase).
print(a.expandtabs(4)) #The expandtabs() method replaces all tab characters in the string with spaces. The number of spaces used to replace each tab character can be specified as an argument. In this case, it will replace the tab character in "Strawberry\tSWEET" with 4 spaces, resulting in "Strawberry    SWEET".
print(a.find("berry")) #The find() method searches for a specified substring within the string and returns the index of the first occurrence. In this case, it searches for the substring "berry" in the string "Strawberry SWEET". The result will be 5, as "berry" starts at index 5 in the string.
print(a.format()) #The format() method is used to format strings by replacing placeholders with specified values. In this case, since there are no placeholders in the string "Strawberry SWEET", it will simply return the original string.
print(a.format_map({})) #The format_map() method is similar to the format() method but takes a mapping (like a dictionary) as an argument to replace placeholders in the string. Since there are no placeholders in the string "Strawberry SWEET", it will simply return the original string.
print(a.index("SWEET")) #The index() method searches for a specified substring within the string and returns the index of the first occurrence. In this case, it searches for the substring "SWEET" in the string "Strawberry SWEET". The result will be 11, as "SWEET" starts at index 11 in the string.
print(a.isalnum()) #The isalnum() method checks if all characters in the string are alphanumeric (letters and numbers) and returns True or False. In this case, it will return False, as the string "Strawberry SWEET" contains a space character, which is not alphanumeric.
print(a.isalpha()) #The isalpha() method checks if all characters in the string are alphabetic (letters) and returns True or False. In this case, it will return False, as the string "Strawberry SWEET" contains a space character, which is not alphabetic.
print(a.isascii()) #The isascii() method checks if all characters in the string are ASCII characters (characters with a Unicode code point less than 128) and returns True or False. In this case, it will return True, as all characters in the string "Strawberry SWEET" are ASCII characters.
print(a.isdecimal()) #The isdecimal() method checks if all characters in the string are decimal characters (0-9) and returns True or False. In this case, it will return False, as the string "Strawberry SWEET" contains letters and a space character, which are not decimal characters.
print(a.isdigit()) #The isdigit() method checks if all characters in the string are digits (0-9) and returns True or False. In this case, it will return False, as the string "Strawberry SWEET" contains letters and a space character, which are not digits.
print(a.isidentifier()) #The isidentifier() method checks if the string is a valid identifier according to Python's rules for variable names and returns True or False. In this case, it will return False, as the string "Strawberry SWEET" contains a space character, which is not allowed in identifiers.
print(a.islower()) #The islower() method checks if all characters in the string are lowercase and returns True or False. In this case, it will return False, as the string "Strawberry SWEET" contains uppercase letters.
print(a.isnumeric()) #The isnumeric() method checks if all characters in the string are numeric characters and returns True or False. In this case, it will return False, as the string "Strawberry SWEET" contains letters and a space character, which are not numeric characters.
print(a.isprintable()) #The isprintable() method checks if all characters in the string are printable (i.e., not control characters) and returns True or False. In this case, it will return True, as all characters in the string "Strawberry SWEET" are printable.
print(a.isspace()) #The isspace() method checks if all characters in the string are whitespace characters (spaces, tabs, newlines) and returns True or False. In this case, it will return False, as the string "Strawberry SWEET" contains letters and a space character, which is not considered whitespace.
print(a.istitle()) #The istitle() method checks if the string is in title case (i.e., the first letter of each word is uppercase and the rest are lowercase) and returns True or False. In this case, it will return True, as the string "Strawberry SWEET" is in title case.
print(a.isupper()) #The isupper() method checks if all characters in the string are uppercase and returns True or False. In this case, it will return False, as the string "Strawberry SWEET" contains lowercase letters.
print(a.join(["Sugarbit", "Cake"])) #The join() method is used to concatenate a list of strings into a single string, using the original string as a separator. In this case, it will join the strings "Hello" and "World" with "Strawberry SWEET" as the separator, resulting in "HelloStrawberry SWEETWorld".
print(a.ljust(50)) #The ljust() method left-justifies the string within a specified width. In this case, it will left-justify the string "Strawberry SWEET" within a width of 50 characters, padding it with spaces on the right.
print(a.lower()) #The lower() method converts all characters in the string to lowercase. In this case, it will convert "Strawberry SWEET" to "strawberry sweet".
print(a.lstrip()) #The lstrip() method removes leading whitespace characters from the string. In this case, it will remove any leading spaces or tabs from the string "Strawberry SWEET". Since there are no leading whitespace characters, it will return the original string.
print(a.maketrans("SWEET", "sweat")) #The maketrans() method creates a translation table that can be used with the translate() method to replace specified characters in the string. In this case, it will create a translation table that maps "S" to "s", "W" to "w", "E" to "e", and "T" to "t". The resulting translation table can be used to replace these characters in the string.
print(a.partition("SWEET")) #The partition() method splits the string into three parts based on the first occurrence of a specified separator. In this case, it will split the string "Strawberry SWEET" into three parts: the part before "SWEET", the separator itself, and the part after "SWEET". The result will be a tuple: ("Strawberry ", "SWEET", "").
print(a.replace("SWEET", "sour")) #The replace() method replaces all occurrences of a specified substring with another substring. In this case, it will replace "SWEET" with "sour" in the string "Strawberry SWEET", resulting in "Strawberry sour".
print(a.rfind("r")) #The rfind() method searches for the last occurrence of a specified substring within the string and returns the index of that occurrence. In this case, it searches for the last occurrence of the letter "r" in the string "Strawberry SWEET". The result will be 8, as the last "r" appears at index 8.
print(a.rindex("SWEET")) #The rindex() method searches for the last occurrence of a specified substring within the string and returns the index of that occurrence. In this case, it searches for the last occurrence of the substring "SWEET" in the string "Strawberry SWEET". The result will be 11, as "SWEET" starts at index 11 in the string.
print(a.rjust(50)) #The rjust() method right-justifies the string within a specified width. In this case, it will right-justify the string "Strawberry SWEET" within a width of 50 characters, padding it with spaces on the left.
print(a.rstrip()) #The rstrip() method removes trailing whitespace characters from the string. In this case, it will remove any trailing spaces or tabs from the string "Strawberry SWEET". Since there are no trailing whitespace characters, it will return the original string.
print(a.rsplit()) #The rsplit() method splits the string into a list of substrings based on a specified separator, starting from the right. In this case, since no separator is specified, it will split the string "Strawberry SWEET" into a list of words: ["Strawberry", "SWEET"].
print(a.split()) #The split() method splits the string into a list of substrings based on a specified separator. In this case, since no separator is specified, it will split the string "Strawberry SWEET" into a list of words: ["Strawberry", "SWEET"].
print(b.splitlines()) #The splitlines() method splits the string into a list of lines based on line breaks. In this case, since there are no line breaks in the string "Sweet\bSugarbit", it will return a list containing the original string: ["Sweet\bSugarbit"].
print(a.startswith("Strawberry")) #The startswith() method checks if the string starts with a specified prefix. In this case, it checks if the string "Strawberry SWEET" starts with "Strawberry". The result will be True, as the string does indeed start with "Strawberry".
print(a.strip()) #The strip() method removes leading and trailing whitespace characters from the string. In this case, it will remove any leading or trailing spaces or tabs from the string "Strawberry SWEET". Since there are no leading or trailing whitespace characters, it will return the original string.
print(a.swapcase()) #The swapcase() method converts all uppercase characters in the string to lowercase and all lowercase characters to uppercase. In this case, it will convert "Strawberry SWEET" to "sTRAWBERRY sweet".
print(a.title()) #The title() method converts the first character of each word in the string to uppercase and the rest to lowercase. In this case, it will convert "Strawberry SWEET" to "Strawberry Sweet".   
print(a.translate(a.maketrans("SWEET", "sweat"))) #The translate() method is used to replace specified characters in the string based on a translation table created using the maketrans() method. In this case, it will replace "S" with "s", "W" with "w", "E" with "e", and "T" with "t" in the string "Strawberry SWEET", resulting in "Strawberry sweat".
print(a.upper()) #The upper() method converts all characters in the string to uppercase. In this case, it will convert "Strawberry SWEET" to "STRAWBERRY SWEET".
print(a.zfill(50)) #The zfill() method pads the string with zeros on the left until it reaches a specified width. In this case, it will pad the string "Strawberry SWEET" with zeros on the left until it reaches a width of 50 characters.

print('welcome'.upper())